# ---------------------------------------------------------------------------
# Shared helpers, config-derived constants and the samples table.
# Included first by the Snakefile; everything below is available to every
# other .smk in the workflow.
# ---------------------------------------------------------------------------

from pathlib import Path

from snakemake.utils import validate

PATHS = config["paths"]
SEED = config["seed"]
PHASES = config["phases"]

ALL_PHASES = [
    "acquire",
    "annotate",
    "qc",
    "landscape",
    "contexture",
    "checkpoints",
    "crosstalk",
    "survival",
    "fair",
]

# --- samples.tsv -----------------------------------------------------------
# Generated by P0-T3 and then committed. Until it exists the DAG is empty by
# design, so the workflow must parse cleanly without it rather than crash.
SAMPLES = None
SAMPLES_TSV = Path(config["samples"]["tsv"])

if SAMPLES_TSV.exists():
    import pandas as pd

    SAMPLES = pd.read_csv(SAMPLES_TSV, sep="\t", dtype=str)

    # dtype=str keeps patient_id and the AOI codes as written — "P1" must not
    # become 1, and a code like "03" must not lose its zero. But the schema
    # declares the flag columns boolean, and dtype=str hands them over as the
    # strings "True" and "False", which fails validation. Coerce them back
    # (the slash-separated form of that phrase trips snakemake --lint, which
    # reads it as an absolute path — hence the wording)
    # explicitly, and fail on anything that is neither: a silent NaN here would
    # mean an AOI quietly stopped being marked as a replicate.
    for _col in ("replicate_flag", "is_control"):
        if _col not in SAMPLES.columns:
            continue
        _mapped = SAMPLES[_col].map({"True": True, "False": False})
        if _mapped.isna().any():
            _bad = sorted(set(SAMPLES.loc[_mapped.isna(), _col]))
            raise WorkflowError(
                f"{SAMPLES_TSV}: column {_col} must be True or False, got {_bad}."
            )
        SAMPLES[_col] = _mapped

    validate(SAMPLES, "../schemas/samples.schema.yaml")
    N_EXPECTED = config["samples"]["expected_n_aoi"]
    if len(SAMPLES) != N_EXPECTED:
        raise WorkflowError(
            f"{SAMPLES_TSV}: expected {N_EXPECTED} AOIs, found {len(SAMPLES)}. "
            "The design table in PROJECT_PLAN §2.1 is authoritative — fix the "
            "parser (P0-T3), do not adjust expected_n_aoi to match."
        )


def targets(*phase_names):
    """Union of the target lists of the named phases, honouring config switches.

    A phase contributes nothing unless its switch is on AND its .smk has
    populated the corresponding TARGETS_* list. Both conditions are needed:
    the switch is the user's intent, the list is what actually exists.
    """
    collected = []
    for name in phase_names:
        if not PHASES.get(name, False):
            continue
        collected.extend(globals().get(f"TARGETS_{name.upper()}", []))
    return collected
