# ---------------------------------------------------------------------------
# Shared helpers, config-derived constants and the samples table.
# Included first by the Snakefile; everything below is available to every
# other .smk in the workflow.
# ---------------------------------------------------------------------------

from pathlib import Path

from snakemake.utils import validate

PATHS = config["paths"]
SEED = config["seed"]
PHASES = config["phases"]

ALL_PHASES = [
    "acquire",
    "annotate",
    "qc",
    "landscape",
    "contexture",
    "checkpoints",
    "crosstalk",
    "survival",
    "fair",
]

# --- samples.tsv -----------------------------------------------------------
# Generated by P0-T3 and then committed. Until it exists the DAG is empty by
# design, so the workflow must parse cleanly without it rather than crash.
SAMPLES = None
SAMPLES_TSV = Path(config["samples"]["tsv"])

if SAMPLES_TSV.exists():
    import pandas as pd

    SAMPLES = pd.read_csv(SAMPLES_TSV, sep="\t", dtype=str)

    # dtype=str keeps patient_id and the AOI codes as written — "P1" must not
    # become 1, and a code like "03" must not lose its zero. But the schema
    # declares the flag columns boolean, and dtype=str hands them over as the
    # strings "True" and "False", which fails validation. Coerce them back
    # (the slash-separated form of that phrase trips snakemake --lint, which
    # reads it as an absolute path — hence the wording)
    # explicitly, and fail on anything that is neither: a silent NaN here would
    # mean an AOI quietly stopped being marked as a replicate.
    for _col in ("replicate_flag", "is_control"):
        if _col not in SAMPLES.columns:
            continue
        _mapped = SAMPLES[_col].map({"True": True, "False": False})
        if _mapped.isna().any():
            _bad = sorted(set(SAMPLES.loc[_mapped.isna(), _col]))
            raise WorkflowError(
                f"{SAMPLES_TSV}: column {_col} must be True or False, got {_bad}."
            )
        SAMPLES[_col] = _mapped

    validate(SAMPLES, "../schemas/samples.schema.yaml")
    N_EXPECTED = config["samples"]["expected_n_aoi"]
    if len(SAMPLES) != N_EXPECTED:
        raise WorkflowError(
            f"{SAMPLES_TSV}: expected {N_EXPECTED} AOIs, found {len(SAMPLES)}. "
            "The design table in PROJECT_PLAN §2.1 is authoritative — fix the "
            "parser (P0-T3), do not adjust expected_n_aoi to match."
        )


# --- signatures.yaml -------------------------------------------------------
# P2-T1. Loaded and validated here rather than inside the scoring script, for
# the same reason samples.tsv is: a malformed gene set should fail at parse,
# not three rules later.
#
# It is a separate file from config.yaml deliberately. config.yaml is a
# declared input of p0t7_assemble_h5ad, so editing it rebuilds the .h5ad and
# re-runs everything downstream including P1-T3's ~25-minute fit. Editing a
# gene set must not cost that.
SIGNATURES = None
SIGNATURES_YAML = Path(config["contexture"]["signatures_yaml"])

if SIGNATURES_YAML.exists():
    import yaml

    with open(SIGNATURES_YAML, encoding="utf-8") as _handle:
        _signature_doc = yaml.safe_load(_handle)

    validate(_signature_doc, "../schemas/signatures.schema.yaml")
    SIGNATURES = _signature_doc["signatures"]

    # The schema enforces uniqueItems within a set but says nothing across
    # sets, and overlap is legitimate here — TIGIT and CTLA4 are in both
    # `exhaustion` and the Phase 3 checkpoint panel. Recorded, not rejected, so
    # a reader of the scores knows two sets are not independent draws.
    SIGNATURE_OVERLAP = {}
    _names = sorted(SIGNATURES)
    for _i, _a in enumerate(_names):
        for _b in _names[_i + 1 :]:
            _shared = set(SIGNATURES[_a]["genes"]) & set(SIGNATURES[_b]["genes"])
            if _shared:
                SIGNATURE_OVERLAP[(_a, _b)] = sorted(_shared)


# --- checkpoints.yaml ------------------------------------------------------
# P3-T1. Same contract as SIGNATURES above: loaded and validated here so a
# malformed panel fails at parse rather than three rules later, and kept in its
# own file because config.yaml is a declared input of p0t7_assemble_h5ad and a
# panel edit must not cost a Phase 1 + Phase 2 rebuild.
#
# The panel is PRE-REGISTERED (ADR 0015). Nothing downstream may filter it by
# detection: which genes turn out to be measurable is the Phase 3 result, not a
# Phase 3 input.
CHECKPOINTS = None
CHECKPOINTS_YAML = Path(config["checkpoints"]["panel_yaml"])

if CHECKPOINTS_YAML.exists():
    import yaml

    with open(CHECKPOINTS_YAML, encoding="utf-8") as _handle:
        _checkpoint_doc = yaml.safe_load(_handle)

    validate(_checkpoint_doc, "../schemas/checkpoints.schema.yaml")
    CHECKPOINTS = _checkpoint_doc["checkpoints"]

    # Five panel genes (PDCD1, CTLA4, LAG3, HAVCR2, TIGIT) are also members of
    # the `exhaustion` signature. Recorded, never rejected — the same rule
    # SIGNATURE_OVERLAP applies within signatures.yaml. A reader comparing the
    # Phase 2 and Phase 3 tables needs to know they are not independent draws,
    # and Phase 2 measured `exhaustion` at 1 of 6 genes in brain, so the overlap
    # is also the best available prior on what Phase 3 will find.
    CHECKPOINT_SIGNATURE_OVERLAP = {}
    if SIGNATURES is not None:
        for _name in sorted(SIGNATURES):
            _shared = set(SIGNATURES[_name]["genes"]) & set(CHECKPOINTS)
            if _shared:
                CHECKPOINT_SIGNATURE_OVERLAP[_name] = sorted(_shared)


# --- external_validation.yaml ----------------------------------------------
# P3-T2b. The source publication's supplementary files, used as an EXTERNAL
# comparator for layers['q3'].
#
# The path is a LITERAL here, not config["..."], and that is the point: pointing
# at this file from config/config.yaml would change config.yaml's SHA-256, which
# is recorded in the .h5ad `uns` and would rebuild Phases 1 and 2 (ADR 0013).
# Phase 3 paid that once at f1f55b8. Same reasoning that keeps checkpoints.yaml
# out of config.yaml, applied one step further.
#
# Guarded by exists() like SAMPLES and CHECKPOINTS above, so the workflow parses
# cleanly on a checkout that has not fetched the supplementary files.
EXTERNAL_VALIDATION = None
EXTERNAL_VALIDATION_YAML = Path("config/external_validation.yaml")

if EXTERNAL_VALIDATION_YAML.exists():
    import yaml

    with open(EXTERNAL_VALIDATION_YAML, encoding="utf-8") as _handle:
        _external_doc = yaml.safe_load(_handle)

    validate(_external_doc, "../schemas/external_validation.schema.yaml")
    EXTERNAL_VALIDATION = _external_doc["external_validation"]

    # Cross-reference sheets against artifacts at LOAD time. The schema can
    # enforce that `artifact` is a string; only this can enforce that it names
    # something. Failing here costs a parse; failing at read time costs a 45 MB
    # download first.
    for _sheet, _spec in sorted(EXTERNAL_VALIDATION["sheets"].items()):
        if _spec["artifact"] not in EXTERNAL_VALIDATION["artifacts"]:
            raise ValueError(
                f"external_validation.sheets.{_sheet}.artifact = "
                f"'{_spec['artifact']}' does not name an entry in "
                f"external_validation.artifacts "
                f"({sorted(EXTERNAL_VALIDATION['artifacts'])})."
            )

    # Two artifacts sharing a `dest` would collide in resources/supplementary/
    # and the wildcard rule would offer to produce the same path twice. Same
    # check REF_KEY_BY_DEST makes for the Phase 2 reference matrices.
    EXTERNAL_KEY_BY_DEST = {
        _spec["dest"]: _key
        for _key, _spec in EXTERNAL_VALIDATION["artifacts"].items()
    }
    if len(EXTERNAL_KEY_BY_DEST) != len(EXTERNAL_VALIDATION["artifacts"]):
        raise ValueError(
            "config external_validation.artifacts: two artifacts share a "
            "`dest` filename."
        )



# --- ligand_receptor.yaml --------------------------------------------------
# P4-T2. The pinned ligand–receptor interaction database Phase 4 draws its
# panel from, PRE-REGISTERED in ADR 0021 §2 and committed before the first
# Phase 4 rule ran.
#
# Same contract as CHECKPOINTS and EXTERNAL_VALIDATION above: loaded and
# validated here so a malformed manifest fails at parse rather than after a
# 1.5 MB download, and guarded by exists() so the workflow parses cleanly on a
# checkout that has not fetched it.
#
# The path comes from config["crosstalk"]["lr_yaml"] rather than being a literal
# — unlike EXTERNAL_VALIDATION, whose path is hardcoded in 05_checkpoints.smk.
# The difference is not an inconsistency: Phase 4 had to edit config.yaml once
# anyway to add its `crosstalk:` block (ADR 0021 Consequences), so naming the
# file there costs nothing, whereas P3-T2b would have paid a whole Phase 1–2
# rebuild for the same key. What both share is the thing that matters — the
# DATABASE PIN itself lives outside config.yaml, so re-pinning never rebuilds
# the .h5ad.
LIGAND_RECEPTOR = None
LIGAND_RECEPTOR_YAML = Path(config["crosstalk"]["lr_yaml"])

if LIGAND_RECEPTOR_YAML.exists():
    import yaml

    with open(LIGAND_RECEPTOR_YAML, encoding="utf-8") as _handle:
        _lr_doc = yaml.safe_load(_handle)

    validate(_lr_doc, "../schemas/ligand_receptor.schema.yaml")
    LIGAND_RECEPTOR = _lr_doc["ligand_receptor"]

    # Two artifacts sharing a `dest` would collide in resources/ligand_receptor/
    # and the wildcard fetch rule would offer to produce the same path twice.
    # The same check REF_KEY_BY_DEST and EXTERNAL_KEY_BY_DEST make.
    LR_KEY_BY_DEST = {
        _spec["dest"]: _key
        for _key, _spec in LIGAND_RECEPTOR["artifacts"].items()
    }
    if len(LR_KEY_BY_DEST) != len(LIGAND_RECEPTOR["artifacts"]):
        raise ValueError(
            "config ligand_receptor.artifacts: two artifacts share a `dest` "
            "filename."
        )

    # The `expect` block is asserted against the parsed database by
    # p4t2c_resolve_lr_pairs, but one class of error is catchable here, for
    # free, before anything is downloaded: an exclusion naming a class the
    # manifest does not itself expect to exist. That is a typo, and a silently
    # ineffective exclusion would inflate the detection filter's before/after
    # gap — the exact number ADR 0021 §2 exists to keep honest.
    _known = set(LIGAND_RECEPTOR["expect"]["annotations"])
    _unknown = sorted(set(LIGAND_RECEPTOR["exclude_annotations"]) - _known)
    if _unknown:
        raise ValueError(
            f"config ligand_receptor.exclude_annotations names {_unknown}, "
            f"which is absent from expect.annotations ({sorted(_known)}). An "
            "exclusion that matches nothing is a typo, and it would quietly "
            "move non-protein interactions into the detection filter's "
            "denominator."
        )


# The language audit scans every tracked file, which Snakemake cannot express as
# an `input:` list without enumerating the repository into the DAG. Without a
# trigger it would run once and then never again — and a check that goes stale
# the moment someone edits a doc is worse than no check, because the green
# output keeps asserting something nobody re-tested.
#
# So its trigger is a digest of what it actually scans, computed at parse time.
# Params are a rerun trigger in Snakemake 8, so editing any tracked prose
# re-runs the audit and nothing else.
def _tracked_text_digest():
    import hashlib
    import subprocess

    skip = {".png", ".pdf", ".h5ad", ".rda", ".RData", ".gz", ".tar", ".xlsx",
            ".sha256", ".lock", ".ipynb"}
    try:
        tracked = subprocess.run(
            ["git", "ls-files"], capture_output=True, text=True, check=True
        ).stdout.split("\n")
    except Exception:
        # No git (a tarball export, say). The audit still runs; it just cannot
        # detect a change, which is the honest degradation rather than a crash.
        return "no-git"
    h = hashlib.sha256()
    for f in sorted(tracked):
        if not f or Path(f).suffix in skip or f.startswith("results/"):
            continue
        h.update(f.encode())
        try:
            h.update(Path(f).read_bytes())
        except OSError:
            continue
    return h.hexdigest()

def targets(*phase_names):
    """Union of the target lists of the named phases, honouring config switches.

    A phase contributes nothing unless its switch is on AND its .smk has
    populated the corresponding TARGETS_* list. Both conditions are needed:
    the switch is the user's intent, the list is what actually exists.
    """
    collected = []
    for name in phase_names:
        if not PHASES.get(name, False):
            continue
        collected.extend(globals().get(f"TARGETS_{name.upper()}", []))
    return collected
